#! /bin/bash

PROG=$0
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

function error_exit {
    echo
    echo "$@"
    exit 1
}
#Trap the killer signals so that we can exit with a good message.
trap "error_exit 'Received signal SIGHUP'" SIGHUP
trap "error_exit 'Received signal SIGINT'" SIGINT
trap "error_exit 'Received signal SIGTERM'" SIGTERM

shopt -s expand_aliases
alias die='error_exit "Error $PROG (@`echo $(( $LINENO - 1 ))`):"'

REPOS=

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -r|--repositories)
      REPOS="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      die "unknown argument $1"
      ;;
  esac
done

[ -z "$REPOS" ] && die "--repositories not specified"

WORK=${SCRIPT_DIR}/../work/${REPOS}/
WORKTEMP=/tmp/codecleanup
[ -d "/zram" ] && WORK=/zram/codecleanup/${REPOS}/
[ -d "/zram" ] && WORKTEMP=/zram/.tmp/codecleanup/${REPOS}/
LOGS=${SCRIPT_DIR}/../logs/${REPOS}/
LOG_FILE=${LOGS}/cleanup.log
LAST_LOG_FILE=${LOGS}/cleanup.old
REPOS_LIST=${SCRIPT_DIR}/config/${REPOS}/repos.lst
POWERSHELL=${SCRIPT_DIR}/scripts/powershell/CodeCleanup.ps1

# OVERRIDE NUGET LOCATIONS
[ -d "/zram" ] && NUGET_PACKAGES=/zram/.nuget/packages/${REPOS}/packages
[ -d "/zram" ] && NUGET_HTTP_CACHE_PATH=/zram/.nuget/packages/${REPOS}/cache
[ -d "/zram" ] && NUGET_PLUGINS_CACHE_PATH=/zram/.nuget/packages/${REPOS}/plugins-cache

echo "Work: ${WORK}"
echo "Temp: ${WORKTEMP}"
echo "Logs: ${LOGS}"
echo "Repos.lst: ${REPOS_LIST}"
echo "Powershell: ${POWERSHELL}"

echo "Path: ${PATH}"

[ ! -d "${LOGS}" ] && mkdir -p ${LOGS}
[ ! -d "${WORK}" ] && mkdir -p ${WORK}
[ ! -d "${WORKTEMP}" ] && mkdir -p ${WORKTEMP}

[ ! -f "${REPOS_LIST}" ] && die "${REPOS_LIST} does not exist"

[ -f "${LAST_LOG_FILE}" ] && rm ${LAST_LOG_FILE}
[ -f "${LOG_FILE}" ] && mv ${LOG_FILE} ${LAST_LOG_FILE}

echo "Changing to ${SCRIPT_DIR}"
cd ${SCRIPT_DIR}
echo "Running: dotnet pwsh -file ${POWERSHELL} -repos ${REPOS_LIST} -work ${WORK} -tempFolder ${WORKTEMP}"
dotnet pwsh -file ${POWERSHELL} -repos ${REPOS_LIST} -work ${WORK} -tempFolder ${WORKTEMP} > ${LOG_FILE} 2>&1
echo "Done"
