
services:
  cache-nuget:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: upgrader-cache-nuget
    hostname: nuget
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://api.nuget.org
      - Proxy__PublicUrl=https://api.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/api.nuget.local:/data
    networks:
      - nuget-cache

  cache-funfair-release:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: upgrader-cache-funfair-release
    hostname: funfair-release
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget
      - Proxy__PublicUrl=https://funfair.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/funfair.nuget.local:/data
    networks:
      - nuget-cache

  cache-funfair-prerelease:
    image: docker-registry.markridgwell.com/credfeto/nuget-proxy:latest
    container_name: upgrader-cache-funfair-prerelease
    hostname: funfair-prerelease
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    environment:
      - Proxy__UpstreamUrl__0=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com
      - Proxy__UpstreamUrl__1=https://s3.eu-west-1.amazonaws.com/dotnet-nuget-prerelease
      - Proxy__PublicUrl=https://funfair.nuget.local:5555
      - Proxy__Packages=/data
    volumes:
      - /cache/nuget/funfair.nuget.local:/data
    networks:
      - nuget-cache

  cache-nuget-nginx:
    image: nginx:stable-alpine
    container_name: upgrader-cache-nuget-nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nuget/certs:/etc/nginx/ssl
      - $CACHE_ROOT/nginx:/var/cache/nginx/proxy
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      cache-nuget:
        condition: service_healthy
      cache-funfair-prerelease:
        condition: service_healthy
      cache-funfair-release:
        condition: service_healthy
    networks:
      nuget-cache:
      updaters:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local

  templates-personal:
    build: ./templates
    container_name: upgrader-templates-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/personal:/local/tracking
      - $CACHE_ROOT/templateupdate/personal/nuget:/local/.nuget/packages/packages
      - $CACHE_ROOT/templateupdate/personal/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

  templates-funfair:
    build: ./templates
    container_name: upgrader-templates-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/funfair:/local/tracking
      - $CACHE_ROOT/templateupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/templateupdate/funfair/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

  packages-personal:
    build: ./packages
    container_name: upgrader-packages-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/personal:/local/tracking
      - $CACHE_ROOT/packageupdate/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/personal/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

  packages-funfair:
    build: ./packages
    container_name: upgrader-packages-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/funfair:/local/tracking
      - $CACHE_ROOT/packageupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/funfair/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

  cleanup-personal:
    build: ./cleanup
    container_name: upgrader-cleanup-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/personal:/local/tracking
      - $CACHE_ROOT/codecleanup/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/personal/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

  cleanup-funfair:
    build: ./cleanup
    container_name: upgrader-cleanup-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/funfair:/local/tracking
      - $CACHE_ROOT/codecleanup/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/funfair/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_healthy
    networks:
      - updaters

networks:
  nuget-cache:
    driver: bridge

  updaters:
    driver: bridge