
services:

  templates-personal:
    build: ./templates
    container_name: upgrader-templates-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/personal-repos.config
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://updates.markridgwell.com/personal-release.config
      - TEMPLATE_CONFIG=https://updates.markridgwell.com/personal-templates.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/personal:/local/tracking
      - $CACHE_ROOT/templateupdate/personal/nuget:/local/.nuget/packages/packages
      - $CACHE_ROOT/templateupdate/personal/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/personal/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/templateupdate/personal/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  templates-funfair:
    build: ./templates
    container_name: upgrader-templates-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/funfair-repos.config
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://updates.markridgwell.com/funfair-release.config
      - TEMPLATE_CONFIG=https://updates.markridgwell.com/personal-templates.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/funfair:/local/tracking
      - $CACHE_ROOT/templateupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/templateupdate/funfair/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/funfair/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/templateupdate/funfair/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  packages-personal:
    build: ./packages
    container_name: upgrader-packages-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/personal-repos.config
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://updates.markridgwell.com/personal-release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/personal:/local/tracking
      - $CACHE_ROOT/packageupdate/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/personal/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/personal/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/packageupdate/personal/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  packages-funfair:
    build: ./packages
    container_name: upgrader-packages-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/funfair-repos.config
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://updates.markridgwell.com/funfair-release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/funfair:/local/tracking
      - $CACHE_ROOT/packageupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/funfair/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/funfair/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/packageupdate/funfair/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  cleanup-personal:
    build: ./cleanup
    container_name: upgrader-cleanup-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/personal-repos.config
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://updates.markridgwell.com/personal-release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/personal:/local/tracking
      - $CACHE_ROOT/codecleanup/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/personal/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/personal/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/codecleanup/personal/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  cleanup-funfair:
    build: ./cleanup
    container_name: upgrader-cleanup-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://updates.markridgwell.com/packages.config
      - REPOS_LIST=https://updates.markridgwell.com/funfair-repos.config
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://updates.markridgwell.com/funfair-release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/funfair:/local/tracking
      - $CACHE_ROOT/codecleanup/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/funfair/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/funfair/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/codecleanup/funfair/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  dependencies-personal:
    build: ./dependencies
    container_name: upgrader-dependencies-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - REPOS_LIST=https://updates.markridgwell.com/personal-repos.config
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/dependencies/personal:/local/tracking
      - $CACHE_ROOT/dependencies/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/dependencies/personal/work:/local/work
      - $CONFIG_ROOT/dependencies/ssh:/local/.ssh:r
      - $CONFIG_ROOT/dependencies/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/dependencies/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/dependencies/personal/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/dependencies/personal/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

  dependencies-funfair:
    build: ./dependencies
    container_name: upgrader-dependencies-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - REPOS_LIST=https://updates.markridgwell.com/funfair-repos.config
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/dependencies/funfair:/local/tracking
      - $CACHE_ROOT/dependencies/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/dependencies/funfair/work:/local/work
      - $CONFIG_ROOT/dependencies/ssh:/local/.ssh:r
      - $CONFIG_ROOT/dependencies/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/dependencies/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/dependencies/funfair/installed:/local/dotnet
      - $DOTNET_CACHE_ROOT/dependencies/funfair/downloads:/local/downloads
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/NuGet.Config:/root/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs:r
    networks:
      - updaters

networks:
  updaters:
    driver: bridge
