
services:
  cache-postgresql:
    container_name: cache-postgresql
    hostname: cache-postgresql
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nuget
      POSTGRES_PASSWORD: nuget
    volumes:
      - /cache/baget/db/postgresql:/var/lib/postgresql/data
    networks:
      - nuget-cache

  cache-nuget:
    image: bagetter/bagetter:latest
    container_name: cache-nuget
    restart: unless-stopped
    stop_grace_period: 15s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=cache-postgresql;Port=5432;Database=nuget;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel__Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - $CACHE_ROOT/baget/security/nuget:/root/.aspnet
      - $CACHE_ROOT/baget/packages/nuget:/data/packages
      - $CACHE_ROOT/baget/db/nuget:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      cache-postgresql:
        condition: service_started
    networks:
      - nuget-cache

  cache-funfair-release:
    image: bagetter/bagetter:latest
    container_name: cache-funfair-release
    restart: unless-stopped
    stop_grace_period: 15s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=cache-postgresql;Port=5432;Database=funfair-release;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel_Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://dotnet-nuget.s3.eu-west-1.amazonaws.com/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - $CACHE_ROOT/baget/security/nuget:/root/.aspnet
      - $CACHE_ROOT/baget/packages/funfair-release:/data/packages
      - $CACHE_ROOT/baget/db/funfair-release:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      cache-postgresql:
        condition: service_started
    networks:
      - nuget-cache

  cache-funfair-prerelease:
    image: bagetter/bagetter:latest
    container_name: cache-funfair-prerelease
    restart: unless-stopped
    stop_grace_period: 15s
    stop_signal: SIGINT
    environment:
      - AllowPackageOverwrites=true
      - ApiKey=Upload
      - Database__ConnectionString=Server=cache-postgresql;Port=5432;Database=funfair-prerelease;User Id=nuget;Password=nuget;
      - Database__Type=PostgreSql
      - Logging__Console__LogLevel_Default=Warning
      - MaxPackageSizeGiB=10
      - MaxVersionsPerPackage=5
      - Mirror__Enabled=true
      - Mirror__PackageDownloadTimeoutSeconds=60000
      - Mirror__PackageSource=https://dotnet-nuget-prerelease.s3.eu-west-1.amazonaws.com/index.json
      - PackageDeletionBehavior=HardDelete
      - Search__Type=Database
      - Storage__Path=/data/packages
      - Storage__Type=FileSystem
    volumes:
      - $CACHE_ROOT/baget/security/nuget:/root/.aspnet
      - $CACHE_ROOT/baget/packages/funfair-prerelease:/data/packages
      - $CACHE_ROOT/baget/db/funfair-prerelease:/data/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      cache-postgresql:
        condition: service_started
    networks:
      - nuget-cache

  cache-nuget-nginx:
    image: nginx:stable-alpine
    container_name: cache-nuget-nginx
    restart: unless-stopped
    stop_grace_period: 5s
    stop_signal: SIGINT
    volumes:
      - ./nuget/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nuget/certs:/etc/nginx/ssl
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 5s
      timeout: 4s
      retries: 5
    depends_on:
      cache-nuget:
        condition: service_started
      cache-funfair-prerelease:
        condition: service_started
      cache-funfair-release:
        condition: service_started
    networks:
      nuget-cache:
      updaters:
        aliases:
          - api.nuget.local
          - funfair.nuget.local
          - funfair-prerelease.nuget.local

  templates-personal:
    build: ./templates
    container_name: templates-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/personal:/local/tracking
      - $CACHE_ROOT/templateupdate/personal/nuget:/local/.nuget/packages/packages
      - $CACHE_ROOT/templateupdate/personal/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_started
    networks:
      - updaters

  templates-funfair:
    build: ./templates
    container_name: templates-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/templateupdate/funfair:/local/tracking
      - $CACHE_ROOT/templateupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/templateupdate/funfair/work:/local/work
      - $CONFIG_ROOT/templateupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/templateupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/templateupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/templateupdate/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    networks:
      - updaters

  packages-personal:
    build: ./packages
    container_name: packages-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/personal:/local/tracking
      - $CACHE_ROOT/packageupdate/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/personal/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_started
    networks:
      - updaters

  packages-funfair:
    build: ./packages
    container_name: packages-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/packageupdate/funfair:/local/tracking
      - $CACHE_ROOT/packageupdate/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/packageupdate/funfair/work:/local/work
      - $CONFIG_ROOT/packageupdate/ssh:/local/.ssh:r
      - $CONFIG_ROOT/packageupdate/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/packageupdate/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/packageupdate/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_started
    networks:
      - updaters

  cleanup-personal:
    build: ./cleanup
    container_name: cleanup-personal
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/personal:/local/tracking
      - $CACHE_ROOT/codecleanup/personal/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/personal/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.personal:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/personal:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_started
    networks:
      - updaters

  cleanup-funfair:
    build: ./cleanup
    container_name: cleanup-funfair
    restart: always
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/funfair/repos.lst
      - TEMPLATE=git@github.com:funfair-tech/funfair-server-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - $TRACKING_ROOT/codecleanup/funfair:/local/tracking
      - $CACHE_ROOT/codecleanup/funfair/nuget:/local/.nuget/packages
      - $CACHE_ROOT/codecleanup/funfair/work:/local/work
      - $CONFIG_ROOT/codecleanup/ssh:/local/.ssh:r
      - $CONFIG_ROOT/codecleanup/gnupg.funfair:/local/.gnupg
      - $CONFIG_ROOT/codecleanup/gitconfig:/local/.gitconfig:r
      - $DOTNET_CACHE_ROOT/codecleanup/funfair:/local/dotnet
      - ./nuget/NuGet.Config:/local/.nuget/NuGet/NuGet.Config:r
      - ./nuget/certs:/local/certs
    depends_on:
      cache-nuget-nginx:
        condition: service_started
    networks:
      - updaters

networks:
  nuget-cache:
    driver: bridge

  updaters:
    driver: bridge