
services:
  templates-personal:
    build: ./templates
    container_name: templates-personal
    restart: no
    stop_grace_period: 5s
    stop_signal: SIGINT
    environment:
      - PACKAGES=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/packages.json
      - REPOS_LIST=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/personal/repos.lst
      - TEMPLATE=git@github.com:credfeto/cs-template.git
      - RELEASE=https://github.com/credfeto/auto-update-config/raw/refs/heads/main/release.config
      - DOTNET_CHANNELS=$DOTNET_CHANNELS
    volumes:
      - ./tracking/templates-personal:/local/tracking
      - ./cache/nuget:/local/.nuget
      - ./cache/templates-personal:/local/work
      - ./config/templateupdate/ssh:/local/.ssh:r
      - ./config/templateupdate/gnupg:/local/.gnupg:r
      - ./config/templateupdate/gitconfig:/local/.gitconfig:r
      - ./dotnet/templateupdate/personal:/local/dotnet