#! /bin/sh

USERNAME=$(whoami)

echo "Running as $USERNAME"

sleep 60s

DOTNETINSTALLFOLDER=/zram/$USERNAME/dotnet
DOTNETINSTALLSCRIPT=/zram/$USERNAME/dotnet-install.sh

echo "Installing to $DOTNETINSTALLFOLDER"

[ -d "$DOTNETINSTALLFOLDER" ] && rm -fr "$DOTNETINSTALLFOLDER"
[ ! -d "$DOTNETINSTALLFOLDER" ] && mkdir -p "$DOTNETINSTALLFOLDER"

echo "Update dotnet install scripts"
curl https://dot.net/v1/dotnet-install.sh -L -o "$DOTNETINSTALLSCRIPT"
chmod +x "$DOTNETINSTALLSCRIPT"

echo "Update to latest dotnet core"
$DOTNETINSTALLSCRIPT --install-dir "$DOTNETINSTALLFOLDER" -channel 6.0
$DOTNETINSTALLSCRIPT --install-dir "$DOTNETINSTALLFOLDER" -channel 7.0
$DOTNETINSTALLSCRIPT --install-dir "$DOTNETINSTALLFOLDER" -channel 8.0


echo "Configure dotnet environment"
export PATH="$PATH:/zram/$USERNAME/dotnet"
export PATH="$PATH:/zram/$USERNAME/.dotnet/tools"
export DOTNET_ROOT=/zram/$USERNAME/dotnet
export DOTNET_INSTALL_DIR=/zram/$USERNAME/dotnet
export DotNetCLI_Path=/zram/$USERNAME/dotnet/dotnet

echo "Install/update powershell"
CD=$PWD
cd /zram/$USERNAME/
/zram/$USERNAME/dotnet/dotnet new tool-manifest -o /zram/$USERNAME/
dotnet tool install --local PowerShell
dotnet tool update --local PowerShell
cd "$CD"

echo "Ensuring Required Tools are installed"
dotnet tool install --local FunFair.BuildCheck
dotnet tool install --local FunFair.BuildVersion
dotnet tool install --local Credfeto.Changelog.Cmd
dotnet tool install --local Credfeto.Package.Update
dotnet tool install --local JetBrains.ReSharper.GlobalTools

touch /zram/$USERNAME/dotnet.ready
