#! /bin/sh

PROG=$0
die() {
    echo
    echo "$@"
    exit 1
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
echo "Script Dir: $BASEDIR"

[ -f "$BASEDIR/.env" ] || die ".env is required"

sudo cp "$BASEDIR/systemd-unit/credfeto-batch-updates.service" /etc/systemd/system/
sudo cp "$BASEDIR/systemd-unit/credfeto-batch-updates.timer" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now credfeto-batch-updates.timer
