#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
info "Script Dir: $BASEDIR"

[ -f "$BASEDIR/.env" ] || die ".env is required"

info "Updating systemd scripts"
sudo cp "$BASEDIR/systemd-unit/credfeto-batch-updates.service" /etc/systemd/system/
sudo cp "$BASEDIR/systemd-unit/credfeto-batch-updates.timer" /etc/systemd/system/

info "systemd reload"
sudo systemctl daemon-reload

info "Enable credfeto-batch-updates.timer"
sudo systemctl enable credfeto-batch-updates.timer

info "Start credfeto-batch-updates.timer"
sudo systemctl start credfeto-batch-updates.timer

success "Done"
