#! /bin/bash

PROG=$0
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

function error_exit {
    echo
    echo "$@"
    exit 1
}
#Trap the killer signals so that we can exit with a good message.
trap "error_exit 'Received signal SIGHUP'" SIGHUP
trap "error_exit 'Received signal SIGINT'" SIGINT
trap "error_exit 'Received signal SIGTERM'" SIGTERM

shopt -s expand_aliases
alias die='error_exit "Error $PROG (@`echo $(( $LINENO - 1 ))`):"'

REPOS=

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -r|--repositories)
      REPOS="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      die "unknown argument $1"
      ;;
  esac
done

[ -z "$REPOS" ] && die "--repositories not specified"

TASKNAME=packageupdate
WORK=${SCRIPT_DIR}/../work/${REPOS}/
[ -d "/zram" ] && WORK=/zram/${TASKNAME}/${REPOS}/
LOGS=~/logs/${REPOS}/
LOG_FILE=${LOGS}/packages.log
LAST_LOG_FILE=${LOGS}/packages.old
REPOS_LIST=${SCRIPT_DIR}/config/${REPOS}/repos.lst
POWERSHELL=${SCRIPT_DIR}/scripts/powershell/UpdatePackages.ps1
PACKAGES=${SCRIPT_DIR}/config/packages.json
PACKAGE_CACHE=~/logs/${REPOS}/cache.json
LAST_PACKAGE_CACHE=~/logs/${REPOS}/cache.old

echo "Work: ${WORK}"
echo "Logs: ${LOGS}"
echo "Repos.lst: ${REPOS_LIST}"
echo "Powershell: ${POWERSHELL}"
echo "Packages.json: ${PACKAGES}"

echo "Path: ${PATH}"

[ ! -d "${LOGS}" ] && mkdir -p ${LOGS}
[ ! -d "${WORK}" ] && mkdir -p ${WORK}

[ ! -f "${POWERSHELL}" ] && die "${POWERSHELL} does not exist"
[ ! -f "${REPOS_LIST}" ] && die "${REPOS_LIST} does not exist"
[ ! -f "${PACKAGES}" ] && die "${PACKAGES} does not exist"

[ -f "${LAST_LOG_FILE}" ] && rm ${LAST_LOG_FILE}
[ -f "${LOG_FILE}" ] && mv ${LOG_FILE} ${LAST_LOG_FILE}

[ -f "${LAST_PACKAGE_CACHE}" ] && rm ${LAST_PACKAGE_CACHE}
[ -f "${PACKAGE_CACHE}" ] && mv ${PACKAGE_CACHE} ${LAST_PACKAGE_CACHE}

echo "Changing to ${SCRIPT_DIR}"
cd ${SCRIPT_DIR}

# UPDATE DOTNET SETTINGS
export DOTNET_NOLOGO=true
export DOTNET_PRINT_TELEMETRY_MESSAGE=false
export DOTNET_ReadyToRun=0
export DOTNET_TC_QuickJitForLoops=1
export DOTNET_TieredPGO=1

# OVERRIDE NUGET LOCATIONS
dotnet tool restore --verbosity detailed > "${LOG_FILE}.install" 2>&1
if [ -d "/zram" ] ; then
  export NUGET_PACKAGES=/zram/.nuget/${TASKNAME}/${REPOS}/packages
  echo "Updating NUGET_PACKAGES to ${NUGET_PACKAGES}"
  export NUGET_HTTP_CACHE_PATH=/zram/.nuget/${TASKNAME}/${REPOS}/cache
  echo "Updating NUGET_HTTP_CACHE_PATH to ${NUGET_HTTP_CACHE_PATH}"
  export NUGET_PLUGINS_CACHE_PATH=/zram/.nuget/${TASKNAME}/${REPOS}/plugins-cache
  echo "Updating NUGET_PLUGINS_CACHE_PATH to ${NUGET_PLUGINS_CACHE_PATH}"
  dotnet tool restore --verbosity detailed >> "${LOG_FILE}.install" 2>&1
fi

if [ -f "${LAST_PACKAGE_CACHE}" ] ; then
  echo "Attempting to pre-populate cache with all used packages"
  dotnet pwsh ./UpdatePackagesBuildCache.ps1 -work "${WORK}" -packageCacheToRead "${LAST_PACKAGE_CACHE}" -packageCacheToWrite "${PACKAGE_CACHE}" -packagesToUpdate "${PACKAGES}" > "${LOGFILE}.cache-update"
fi

echo "Running: dotnet pwsh -file ${POWERSHELL} -repos ${REPOS_LIST} -work ${WORK} -trackingFolder ${LOGS} -packageCache ${PACKAGE_CACHE} -packagesToUpdate ${PACKAGES}"
echo "Running: dotnet pwsh -file ${POWERSHELL} -repos ${REPOS_LIST} -work ${WORK} -trackingFolder ${LOGS} -packageCache ${PACKAGE_CACHE} -packagesToUpdate ${PACKAGES}" > ${LOG_FILE}
echo "NUGET_PACKAGES to ${NUGET_PACKAGES}" >> ${LOG_FILE}
echo "NUGET_HTTP_CACHE_PATH to ${NUGET_HTTP_CACHE_PATH}" >> ${LOG_FILE}
echo "Updating NUGET_PLUGINS_CACHE_PATH to ${NUGET_PLUGINS_CACHE_PATH}" >> ${LOG_FILE}
dotnet pwsh -file ${POWERSHELL} -repos ${REPOS_LIST} -work ${WORK} -trackingFolder ${LOGS} -packageCache ${PACKAGE_CACHE} -packagesToUpdate ${PACKAGES} >> ${LOG_FILE} 2>&1
dotnet build-server shutdown
echo "Done"
