#! /bin/sh

sudo rm -fr cache/templateupdate/personal/*
sudo rm -fr cache/templateupdate/funfair/*
sudo rm -fr cache/packageupdate/personal/*
sudo rm -fr cache/packageupdate/funfair/*

sudo rm -fr tracking/templateupdate/personal/*
sudo rm -fr tracking/templateupdate/funfair/*
sudo rm -fr tracking/packageupdate/personal/*
sudo rm -fr tracking/packageupdate/funfair/*


## TODO
# * run a container that creates the internal SSL certs that everything that depends on them needs
# * code-cleanup
# * Simplify folders and what needs to be set up

sudo docker compose rm -f
sudo docker image prune --all --force
sudo docker compose build && sudo docker compose up
