#! /bin/sh

SECTION=$1
USERNAME=$(whoami)

if [ ! -z "$SECTION" ] ; then
 echo "Section not defined!"
 exit -1 
fi

echo "Running as $USERNAME"

DOTNETINSTALLFOLDER="/zram/$USERNAME/$SECTION/dotnet"
DOTNETINSTALLSCRIPT=/zram/$USERNAME/$SECTION/dotnet-install.sh

if [ -d "$DOTNETINSTALLFOLDER" ] ; then

 echo "Configure dotnet environment"
 export PATH="$PATH:/zram/$USERNAME/$SECTION/dotnet"
 export PATH="$PATH:/zram/$USERNAME/$SECTION/.dotnet/tools"
 export DOTNET_ROOT=/zram/$USERNAME/$SECTION/dotnet
 export DOTNET_INSTALL_DIR=/zram/$USERNAME/$SECTION/dotnet
 export DotNetCLI_Path=/zram/$USERNAME/$SECTION/dotnet/dotnet


fi

