#! /bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Scripts: ${SCRIPT_DIR}"
cd ${SCRIPT_DIR}

echo "Fetching latest config repo"
# junk any existing checked out files
git reset HEAD --hard --recurse-submodules
git clean -f -x -d
git checkout master

echo "Getting latest config repo"
git pull --recurse-submodules

echo "Updating tools"
dotnet tool restore
