#! /bin/sh
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

echo "Scripts: ${SCRIPT_DIR}"
cd "${SCRIPT_DIR}"

echo "Fetching latest config repo"
# junk any existing checked out files
git clean -f -x -d
git reset HEAD --hard

echo "Getting latest config repo"
git pull --recurse-submodules
git submodule update --init --force --remote
