#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

BASEDIR="$(dirname "$(readlink -f "$0")")"
info "Script Dir: $BASEDIR"

cd "$BASEDIR" || die "Could not change to $BASEDIR"

[ -f "$BASEDIR/.env" ] || die "$BASEDIR/.env is required"

[ -f "$BASEDIR/nuget/NuGet.Config" ] || die "$BASEDIR/nuget/NuGet.Config is required"

info "Updating Repo"
git pull

info "Using $BASEDIR/.env"
# shellcheck source=/dev/null
. "$BASEDIR/.env"

info "DOTNET_CHANNELS: $DOTNET_CHANNELS"
info "CACHE_ROOT: $CACHE_ROOT"
info "DOTNET_CACHE_ROOT: $DOTNET_CACHE_ROOT"
info "TRACKING_ROOT: $TRACKING_ROOT"

info "PACKAGES: $PACKAGES"
info "REPOS_LIST: $REPOS_LIST"
info "RELEASE: $RELEASE"
info "TEMPLATE_CONFIG: $TEMPLATE_CONFIG"
info "TEMPLATE: $TEMPLATE"
info "COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME"
info "COMPOSE_PROFILE: $COMPOSE_PROFILE"

[ -z "$DOTNET_CHANNELS" ] && die "DOTNET_CHANNELS not defined"
[ -z "$CACHE_ROOT" ] && die "CACHE_ROOT not defined"
[ -z "$DOTNET_CACHE_ROOT" ] && die "DOTNET_CACHE_ROOT not defined"
[ -z "$TRACKING_ROOT" ] && die "TRACKING_ROOT not defined"

[ -z "$PACKAGES" ] && die "PACKAGES not defined"
[ -z "$REPOS_LIST" ] && die "REPOS_LIST not defined"
[ -z "$RELEASE" ] && die "RELEASE not defined"
[ -z "$TEMPLATE_CONFIG" ] && die "TEMPLATE_CONFIG not defined"
[ -z "$TEMPLATE" ] && die "TEMPLATE not defined"
[ -z "$COMPOSE_PROJECT_NAME" ] && die "COMPOSE_PROJECT_NAME not defined"
[ -z "$DOTNET_SOURCE" ] && die "DOTNET_SOURCE not defined"
[ -z "$DOTNET_PROXY_HOST" ] && die "DOTNET_PROXY_HOST not defined"
[ -z "$COMPOSE_PROFILE" ] && COMPOSE_PROFILE=full

info "COMPOSE_PROFILE: $COMPOSE_PROFILE"

COMPOSE_FILE="$BASEDIR/docker-compose.yml"
[ "$COMPOSE_PROFILE" = "minimal" ] && COMPOSE_FILE="$BASEDIR/docker-compose.minimal.yml"
[ "$COMPOSE_PROFILE" = "alt" ] && COMPOSE_FILE="$BASEDIR/docker-compose.alt.yml"

info "Copying scripts to containers"
cp "$BASEDIR/scripts/install-dotnet" "$BASEDIR/cleanup/"
cp "$BASEDIR/scripts/optimise-git" "$BASEDIR/cleanup/"
cp "$BASEDIR/scripts/setup-git" "$BASEDIR/cleanup/"
cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/cleanup/"
cp "$BASEDIR/scripts/setup-certificates" "$BASEDIR/cleanup/"

cp "$BASEDIR/scripts/install-dotnet" "$BASEDIR/dependencies/"
cp "$BASEDIR/scripts/optimise-git" "$BASEDIR/dependencies/"
cp "$BASEDIR/scripts/setup-git" "$BASEDIR/dependencies/"
cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/dependencies/"
cp "$BASEDIR/scripts/setup-certificates" "$BASEDIR/dependencies/"

cp "$BASEDIR/scripts/install-dotnet" "$BASEDIR/packages/"
cp "$BASEDIR/scripts/optimise-git" "$BASEDIR/packages/"
cp "$BASEDIR/scripts/setup-git" "$BASEDIR/packages/"
cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/packages/"
cp "$BASEDIR/scripts/setup-certificates" "$BASEDIR/packages/"

cp "$BASEDIR/scripts/install-dotnet" "$BASEDIR/templates/"
cp "$BASEDIR/scripts/optimise-git" "$BASEDIR/templates/"
cp "$BASEDIR/scripts/setup-git" "$BASEDIR/templates/"
cp "$BASEDIR/scripts/setup-gpg" "$BASEDIR/templates/"
cp "$BASEDIR/scripts/setup-certificates" "$BASEDIR/templates/"

info "Updating docker: $COMPOSE_FILE"
sudo docker compose --file "$COMPOSE_FILE" pull || die "Failed to pull images"

sudo docker compose --file "$COMPOSE_FILE" up -d --remove-orphans || die "Failed to bring up services"

info "Removing old images"
sudo docker image prune -f || die "Failed to prune old images"

success "Done"
