#! /bin/sh
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Scripts: ${SCRIPT_DIR}"
cd ${SCRIPT_DIR}

echo "Getting latest config repo"
# junk any existing checked out files
git reset HEAD --hard --recurse-submodules
git clean -f -x -d
git checkout main
git reset HEAD --hard --recurse-submodules
git clean -f -x -d
git fetch --recurse-submodules

# NOTE Loses all local commits on main
git reset --hard origin/main --recurse-submodules
git remote update origin --prune
git prune
git gc --aggressive --prune

echo "Updating Submodules"
git submodule update --remote
git add -A
git commit -m"Updated Submodules"
git push

echo "Updating tools"
dotnet nuget locals http-cache --clear
dotnet tool restore
dotnet nuget locals http-cache --clear
dotnet tool list --local | awk '{ print $1 }' | tail +3 | xargs -I % sh -c 'dotnet tool update --local %;'

echo "Ensuring Required Tools are installed"
dotnet pwsh scripts/powershell/ToolInstall.ps1 "FunFair.BuildCheck"
dotnet pwsh scripts/powershell/ToolInstall.ps1 "FunFair.BuildVersion"
dotnet pwsh scripts/powershell/ToolInstall.ps1 "Credfeto.Changelog.Cmd"
dotnet pwsh scripts/powershell/ToolInstall.ps1 "Credfeto.Package.Update"

dotnet tool restore
git add -A
git commit -m"Updated Dotnet Tools"
git push
