#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}

GPG_KEY_FILE=$1
[ -z "$GPG_KEY_FILE" ] && die "GPG Key file not specified"

gpg --list-keys || die "Could not list public keys"
gpg --list-secret-keys || die "Could not list secret keys"
if [ -f "$GPG_KEY_FILE" ]; then
  gpg --import "$GPG_KEY_FILE" || die "Could not import secret keys from $HOME/.gnupg/key.asc"
  gpg --list-secret-keys || die "Could not list secret keys"
fi


# disable gpg commit signing
git config --global commit.gpgsign true || die "Could not disable signing"

GIT_USER=$(git config --global user.email)
[ -z "$GIT_USER" ] && die "Git user email not defined"

GPG_KEY_ID=$(gpg --list-keys "$GIT_USER" | grep -E "^\s\s\s\s\s\s([A-Z0-9]+)$" | head -1)

echo "Git email: $GIT_USER"
echo "GPG Key id: $GPG_KEY_ID"

if [ -z "$GPG_KEY_ID" ]; then
  echo "Disabling commit signing"
  git config --global commit.gpgsign false || die "Could not disable signing"
else
  echo "Enabling commit signing"
  git config --global user.signingkey "$GPG_KEY_ID" || die "Could not set key"
  git config --global commit.gpgsign true || die "Could not enable signing"
fi
