#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

for CURRENT_DIR in $(find /local/work/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache)
do
  info "Optimising $CURRENT_DIR..."

  info "Clearing locks..."
  find "$CURRENT_DIR/.git" -name "*.lock"
  [ -f "$CURRENT_DIR/.git/index.lock" ] && rm -f "$CURRENT_DIR/.git/index.lock"
  [ -f "$CURRENT_DIR/.git/objects/info/commit-graph.lock" ] && rm -f "$CURRENT_DIR/.git/objects/info/commit-graph.lock"

  info "Pruning remotes..."
  for REMOTE in $(git -C "$CURRENT_DIR" remote)
  do
    info "Pruning $REMOTE..."
    git -C "$CURRENT_DIR" remote prune "$REMOTE"
  done

  info "Repacking..."
  git -C "$CURRENT_DIR" repack
  info "Pruning packed..."
  git -C "$CURRENT_DIR" prune-packed
  info "Expiring reflog..."
  git -C "$CURRENT_DIR" reflog expire --expire=1.month.ago
  info "Garbage collecting..."
  git -C "$CURRENT_DIR" gc --aggressive --prune --force

done

success "Repo optimisation completed"
