#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}


for line in $(find /local/work/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache)
do
  echo "$line"
  CURRENT_DIR=$line

  echo ""
  echo "Optimising $CURRENT_DIR..."

  echo "* Clearing Locks..."
  find "$CURRENT_DIR/.git" -name "*.lock
  [ -f "$CURRENT_DIR/.git/index.lock" ] && rm -f "$CURRENT_DIR/.git/index.lock"
  [ -f "$CURRENT_DIR/.git/objects/info/commit-graph.lock" ] && rm -f "$CURRENT_DIR/.git/objects/info/commit-graph.lock"


  echo "* Pruning remotes..."
  for REMOTE in $(git -C "$CURRENT_DIR" remote)
  do
    echo "  + Pruning $REMOTE..."
    git -C "$CURRENT_DIR" remote prune "$REMOTE"
  done

  echo "* Repacking..."
  git -C "$CURRENT_DIR" repack
  echo "* Pruning packed..."
  git -C "$CURRENT_DIR" prune-packed
  echo "* Expiring reflog..."
  git -C "$CURRENT_DIR" reflog expire --expire=1.month.ago
  echo "* Garbage collecting..."
  git -C "$CURRENT_DIR" gc --aggressive --prune --force

  echo " * done"

done

echo "Repo optimisation completed"