#! /bin/sh

for line in $(find /local/work/* -name '*.git' -print | sed "s|/.git$||" | sort -u | grep -v .cache)
do
  echo "$line"
  CURRENT_DIR=$line

  echo ""
  echo "Optimising $CURRENT_DIR..."
  git -C "$CURRENT_DIR" gc --aggressive --prune 2>&1

  echo " * done"
done
