#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

GPG_KEY_FILE=$1
[ -z "$GPG_KEY_FILE" ] && die "GPG Key file not specified"

gpg --list-keys || die "Could not list public keys"
gpg --list-secret-keys || die "Could not list secret keys"
if [ -f "$GPG_KEY_FILE" ]; then
  gpg --import "$GPG_KEY_FILE" || die "Could not import secret keys from $GPG_KEY_FILE"
  gpg --list-secret-keys || die "Could not list secret keys"
fi

# disable gpg commit signing
git config --global commit.gpgsign false

GIT_USER=$(git config --global user.email)
[ -z "$GIT_USER" ] && die "Git user email not defined"

GPG_KEY_ID=$(gpg --list-keys "$GIT_USER" | grep -E "^\s{6}([A-Z0-9]+)$" | head -1)

info "Git email: $GIT_USER"
info "GPG Key id: $GPG_KEY_ID"

if [ -z "$GPG_KEY_ID" ]; then
  info "Disabling commit signing"
  git config --global commit.gpgsign false || die "Could not disable signing"
else
  info "Enabling commit signing"
  git config --global user.signingkey "$GPG_KEY_ID" || die "Could not set key"
  git config --global commit.gpgsign true || die "Could not enable signing"
fi

success "GPG configured"
