#! /bin/sh

[ -z "$GIT_USER_NAME" ] && die "GIT_USER_NAME not defiled"
[ -z "$GIT_USER_EMAIL" ] && die "GIT_USER_EMAIL not defiled"
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
git config --global pull.rebase true
git config --global merge.ff false
git config --global rebase.autosquash true
git config --global core.autocrlf false
git config --global core.ignorecase false
git config --global fetch.prune true
git config --global push.autoSetupRemote true
git config --global core.preloadindex true
git config --global core.fscache true

