#! /bin/sh

die() {
    echo
    echo "$@"
    exit 1
}


[ -z "$GIT_USER_NAME" ] && die "GIT_USER_NAME not defiled"
[ -z "$GIT_USER_EMAIL" ] && die "GIT_USER_EMAIL not defiled"
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
git config --global core.autocrlf false
git config --global core.fscache true
git config --global core.ignorecase false
git config --global core.preloadIndex true
git config --global feature.manyFiles true
git config --global fetch.parallel 16
git config --global fetch.prune true
git config --global merge.ff false
git config --global pull.rebase true
git config --global push.autoSetupRemote true
git config --global rebase.autosquash true

# increase the buffer size for Git commands
git config --global core.packedGitLimit 512m
git config --global core.packedGitWindowSize 512m

# Sparse checkout?
# git config --global core.sparseCheckout true

# Rewrite common https urls to the ssh equivalent.
git config --global url."git@github.com:".insteadOf "https://github.com/"
git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"