#! /bin/sh

CERTIFICATES="api.nuget.local funfair.nuget.local funfair-prerelease.nuget.local builds.dotnet.local"

echo "Ensuring certs folder created"
[ -d /usr/share/ca-certificates/local ] && sudo mkdir -p /usr/share/ca-certificates/local

echo "Installing certificates into folders..."

for CERTIFICATE in $CERTIFICATES; do
  echo "* $CERTIFICATE"
  if [ -f "/usr/share/ca-certificates/local/$CERTIFICATE.crt" ]; then
    echo "  -- Copying file"
    sudo cp "$HOME/certs/$CERTIFICATE.crt" "/usr/share/ca-certificates/local/$CERTIFICATE.crt" || die "could not install $CERTIFICATE.crt"
    echo "local/$CERTIFICATE.crt" | sudo tee -a /etc/ca-certificates.conf
  else
    echo "  -- Already installed"
  fi
done

echo "Importing certificates..."
sudo update-ca-certificates --verbose --fresh || die "could not import certificates"


echo echo "Importing certificates completed"