#! /bin/sh

CERTIFICATES="api.nuget.local funfair.nuget.local funfair-prerelease.nuget.local builds.dotnet.local"

echo "Ensuring certs folder created"
[ ! -d /usr/share/ca-certificates/local ] && sudo mkdir -p /usr/share/ca-certificates/local && die "Could not create /usr/share/ca-certificates/local"
[ ! -d /usr/local/share/ca-certificates/local ] && sudo mkdir -p /usr/local/share/ca-certificates/local && die "Could not create /usr/local/share/ca-certificates/local"

echo "Installing certificates into folders..."

for CERTIFICATE in $CERTIFICATES; do
  echo "* $CERTIFICATE"
  echo "  -- Copying file to /usr/share/ca-certificates/local/"
  sudo cp "$HOME/certs/$CERTIFICATE.crt" "/usr/share/ca-certificates/local/$CERTIFICATE.crt" || die "could not install $CERTIFICATE.crt"

  echo "  -- Copying file to /usr/local/share/ca-certificates/local/"
  sudo cp "$HOME/certs/$CERTIFICATE.crt" "/usr/local/share/ca-certificates/local/$CERTIFICATE.crt" || die "could not install $CERTIFICATE.crt"

  INSTALLED=$(grep "local/$CERTIFICATE.crt" /etc/ca-certificates.conf)
  if [ -z "$INSTALLED" ]; then
    echo "  -- Installing Link"
    echo "local/$CERTIFICATE.crt" | sudo tee -a /etc/ca-certificates.conf
  else
    echo "  -- Link already installed"
  fi

  INSTALLED=$(grep "local/$CERTIFICATE.crt" /etc/ca-certificates.conf)
  [ -z "$INSTALLED" ] && die "local/$CERTIFICATE.crt isn't installed"

done

echo "Importing certificates..."
sudo update-ca-certificates --verbose --fresh || die "could not import certificates"


echo echo "Importing certificates completed"