#! /bin/sh

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*" >&2
    exit 1
}

success() {
    printf '\n\033[32m✓\033[0m %s\n' "$*"
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

[ -z "$GIT_USER_NAME" ] && die "GIT_USER_NAME not defined"
[ -z "$GIT_USER_EMAIL" ] && die "GIT_USER_EMAIL not defined"

# User details
git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"

# General settings
git config --global core.autocrlf false
git config --global core.fscache true
git config --global core.ignorecase false
git config --global core.preloadIndex true
git config --global feature.manyFiles true
git config --global fetch.parallel 16
git config --global fetch.prune true
git config --global merge.ff false
git config --global pull.rebase true
git config --global push.autoSetupRemote true
git config --global rebase.autosquash true

# increase the buffer size for Git commands
git config --global core.packedGitLimit 512m
git config --global core.packedGitWindowSize 512m

# Rewrite common https urls to the ssh equivalent.
git config --global url."git@github.com:".insteadOf "https://github.com/"
git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"

success "Git configured"
