---
name: "Build: Cleanup Docker Image"
"on":
  push:
    branches:
      - main
    paths:
      - "cleanup/**/*"
      - "scripts/**/*"
      - "nuget/certs/**/*"
      - .github/workflows/build-cleanup-docker-image.yml

concurrency:
  group: "${{github.workflow}}-${{github.ref}}-cleanup-docker-image"
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

jobs:
  build-cleanup-docker-image:
    env:
      APP_OWNER: credfeto
      APP_NAME: dev-cleanup
      APP_PATH: cleanup

    runs-on: ubuntu-latest
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 1

      - name: "Copy common scripts"
        shell: bash
        run: |
          SCRIPTS="${{github.workspace}}/scripts"
          APP="${{github.workspace}}/${{env.APP_PATH}}"
          cp "$SCRIPTS/install-dotnet" "$APP"
          cp "$SCRIPTS/optimise-git" "$APP"
          cp "$SCRIPTS/setup-certificates" "$APP"
          cp "$SCRIPTS/setup-git" "$APP"
          cp "$SCRIPTS/setup-gpg" "$APP"
          mkdir -p "$APP/certs"
          cp "${{github.workspace}}/nuget/certs"/*.crt "$APP/certs/"

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v4.3.0

      - name: "Docker: Login to GitHub Container Registry"
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}

      - name: "Docker Trust Enable"
        shell: bash
        run: |
          TRUST="${{env.DOCKER_CONTENT_TRUST}}"
          echo "DOCKER_CONTENT_TRUST_ORIGINAL=${TRUST}" >> "$GITHUB_ENV"
          echo "DOCKER_CONTENT_TRUST=1" >> "$GITHUB_ENV"

      - name: "Docker: Test Build"
        uses: docker/build-push-action@v7.3.0
        with:
          context: ${{github.workspace}}/${{env.APP_PATH}}
          platforms: linux/amd64
          load: true
          tags: |
            ${{env.APP_OWNER}}/${{env.APP_NAME}}:test
          provenance: false

      - name: "Docker: Build with tags"
        uses: docker/build-push-action@v7.3.0
        with:
          context: ${{github.workspace}}/${{env.APP_PATH}}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{env.APP_OWNER}}/${{env.APP_NAME}}:latest
          provenance: false

      - name: "Docker Trust Restore"
        shell: bash
        run: |
          TRUST="${{env.DOCKER_CONTENT_TRUST_ORIGINAL}}"
          echo "DOCKER_CONTENT_TRUST=${TRUST}" >> "$GITHUB_ENV"
